config/routes.rb
Rails.application.routes.draw do
  # Errors
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  get 'droplets/index'

  # ActiveAdmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Rivyr
  root to: 'pages#home', as: 'home'
  get '/privacy', to: 'pages#privacy', as: 'privacy'

  # Places
  resources :places, only: [:show, :new, :create] do
    resources :droplets, only: [:show, :create, :update]
  end

  # Droplets
  post '/droplets/:id/vote', to: 'droplets#vote', as: :droplet_vote
  post '/preview', to: 'droplets#preview', as: :prevew

  # Users
  get '/sign_up', to: 'users#new', as: 'new_user'
  resources :users, only: [:create]

  # Search
  get '/search', to: 'places#search', as: 'search'

  # Sessions
  get '/sign_in', to: 'sessions#new', as: 'new_session'
  delete '/sign_out', :to => 'sessions#destroy', as: 'session'
  resources :sessions, only: [:create]

  # Sitemaps
  get "/sitemap.xml", to: redirect { "http://rivyr-production.s3.amazonaws.com/sitemaps/sitemap.xml.gz" }
end

app/views/shared/_actionbar.html.erb
<div class='nav-links hidden-xs'>
  <div class="container-fluid col-lg-10 col-lg-offset-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Browse All', search_path(q:'') %></li>
        <li><%= link_to 'Countries', search_path(q:'', type: 'country') %></li>
        <li><%= link_to 'States', search_path(q:'', type: 'state') %></li>
        <li><%= link_to 'Cities', search_path(q:'', type: 'city') %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Add Place', new_place_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Sign out', session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <% unless sign_up_path? %>
            <li><%= link_to "Sign Up", new_user_path %></li> <% end %>
          <% unless log_in_path? %>
            <li><%= link_to "Log In", new_session_path %></li>
          <% end %>
        <% end %>
      </ul>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% (flash[:alerts] || []).each do |alert| %>
  <div class="alert alert-temp alert-dismissable alert-<%= alert.first %> fade in">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= t alert.last %></strong></a>
  </div>
<% end %>
<% flash.clear %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">

      <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <h4 class="line3 center standart-h4title"><span>navigation</span></h4>
        <ul class="footer-links">
          <li><%= link_to 'home', home_path %></li>
          <li><%= link_to 'add place', new_place_path %></li>
          <li><%= link_to 'privacy', privacy_path %></li>
        </ul>
      </div>

      <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <h4 class="line3 center standart-h4title"><span>social</span></h4>
        <ul class="footer-links">
          <li><a href="https://twitter.com/rivyr_app">twitter</a></li>
          <li><a href="https://www.facebook.com/rivyr">facebook</a></li>
          <li><a href="http://google.com/+rivyr-travel">google+</a></li>
        </ul>
      </div> 

      <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <h4 class="line3 center standart-h4title"><span>reading list</span></h4>
        <ul class="footer-links">
          <li><a href="http://www.adventure-journal.com/">adventure journal</a></li>
          <li><a href="http://www.classetouriste.be/">classe touriste</a></li>
          <li><a href="http://www.hitherandthither.net/">hither & thither</a></li>
          <li><a href="http://www.ahotellife.com/">hotel life</a></li>
          <li><a href="http://roadsandkingdoms.com/">roads and kingdoms</a></li>
        </ul>
      </div>

      <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <h4 class="line3 center standart-h4title"><span>rivyr</span></h4>
        <p>rivyr.com allows passionate explorers to collaboratively write high quality travel guides for every place you'd ever want to explore.</p>
      </div>

    </div><!-- ROW FOOTER-->
    <hr>
    <p>Copyright © 2014 Rivyr.com.</p>
  </div><!-- CONTAINER FOOTER-->

</footer>

app/views/shared/_form_error.html.erb
<p class='text-danger error'><%= text %></p>

app/views/shared/_gtm.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WTD7GB"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WTD7GB');</script>
<!-- End Google Tag Manager -->

app/views/shared/_guide_side_details.html.erb
<%= gravatar_tag droplet.user.email, size: 60, html: {class: 'profile-pic pull-left'} %>
<small>
  <ul>
      <% if droplet.user %><li><%= droplet.user.username %></li><% end %>
      <% if droplet.created_at %><li><span class='glyphicons calendar'></span> <%= time_ago_in_words(droplet.created_at) %> ago</li><% end %>
      <% if controller_name == 'places' %>
        <% if droplet.cached_votes_score > 0 %><li><span class='glyphicons star'></span> <%= pluralize(droplet.cached_votes_total, 'vote') %></li><% end %>
      <% end %>
      <% if controller_name == 'droplets' %>
        <li><span class='glyphicons certificate'></span> <%= droplet.rating %> / 100</li>
      <% end %>
  </ul>
</small>
<% if controller_name == 'places' %>
  <div><%= link_to place_droplet_path(place, droplet.droplet_type), class: 'btn btn-info btn-xs' do -%>Best of <%= droplet.type_count(place) %> droplets<%- end -%></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid col-lg-10 col-lg-offset-1">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag "logo-small.png" %>rivyr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <div class='search-container'>
          <form id="search-form" role="search" action='/search' method='get'>
            <li class='pull-left'><input id='search-query' type='text' name='q' placeholder="Search" value="<%= @keyword %>" /></li>
            <li class='pull-left'><input id='search-scope' type='text' name='q_area' placeholder='In what area?' value="<%= @scope.name if @scope %>" /></li>

            <input id='search-scope-value' type='hidden' name='place_id' value="<%= @scope.id if @scope %>"/>
            <input id='search-submit' type="submit" style="visibility: hidden; position: fixed;"/>
          </form>
        </div>
        <label class='search-button' for='search-submit'><span class='glyphicons search'></span></lable>
      </ul>
      <ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
        <li><%= link_to 'Browse All', search_path(q:'') %></li>
        <li><%= link_to 'Countries', search_path(q:'', type: 'country') %></li>
        <li><%= link_to 'States', search_path(q:'', type: 'state') %></li>
        <li><%= link_to 'Cities', search_path(q:'', type: 'city') %></li>
        <li><%= link_to 'Add place', new_place_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Sign out', session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <% unless sign_up_path? %>
            <li><%= link_to "Sign Up", new_user_path %></li> <% end %>
          <% unless log_in_path? %>
            <li><%= link_to "Log In", new_session_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <div class="col-md-1"></div>
</nav>